/* Generated by nrf-config-diff-cli */

#ifndef APP_CONFIG_H__
#define APP_CONFIG_H__

/* Changed variables */
#define GPIOTE_ENABLED 1
#define GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4
#define NRFX_CLOCK_ENABLED 1
#define NRFX_GPIOTE_ENABLED 1
#define NRF_CLOCK_ENABLED 1
#define APP_TIMER_ENABLED 1
#define BUTTON_ENABLED 1

#endif // APP_CONFIG_H__
